title: Jose Hernández
author: Jose Hernández
twitter: josehernandz
domain: http://josehernandez.xyz

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

paginate: 6

collections:
  - works

gems:
  - jekyll-sitemap